my_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'
end

my_app/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :manage, Post, user_id: user.id
         can :read, :all
       end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

my_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

my_app/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

my_app/app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send
  def welcome_send
    WelcomeMailer.welcome_send(self).deliver
  end
end

my_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, alert: exception.message
  end
end

my_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

my_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

my_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 3)
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  def show
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end
  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

my_app/app/helpers/application_helper.rb
module ApplicationHelper
end

my_app/app/helpers/comments_helper.rb
module CommentsHelper
end

my_app/app/helpers/pages_helper.rb
module PagesHelper
end

my_app/app/helpers/posts_helper.rb
module PostsHelper
end

my_app/app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at)%>Ago</p>
  </div>
    <p><%= link_to "Delete", [comment.post, comment], method: :delete, class: "button", data: {confirm: 'Are you sure?'}%></p>

</div>

my_app/app/views/comments/_form.html.erb
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

my_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sidebar">
      <div id="heading">
          <h1>expressThought</h1>
      </div>


      <ul>
        <li class="category">website</li>
        <li><%= link_to "blog",root_path %></li>
        <li><%= link_to "About",about_path %></li>
      </ul>
      <ul>
        <li class="category">Social</li>
        <li><a href="https://github.com/lakshitdosi">github</a></li>
        <li><a href="https://www.linkedin.com/in/lakshit-dosi-4668bb17a">linkedin</a></li>
        <li><a href="https://www.facebook.com/lxit.dosi">facebook</a></li>
        <li><a href="https://www.instagram.com/lxitdosi/">instagram</a></li>
        <li><a href="https://twitter.com/DosiLakshit?s=08">twitter</a></li>
      </ul>
    </div>
    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>All Posts</p>
        <% elsif current_page?(about_path) %>
          <p>About</p>
        <% else %>
          <%= link_to "Back to All posts", root_path %>
        <% end %>
        <% if user_signed_in? %>
          <div class="buttons">
            <button class="button"><%= link_to "New Post",new_post_path %></button>
            <button class="button"><%= link_to "Logout",destroy_user_session_path, method: :delete %></button>
          </div>
        <% else %>
          <div class="buttons">
            <button class="button"><%= link_to "Signup",new_user_registration_path %></button>
            <button class="button"><%= link_to "Login",new_user_session_path %></button>
          </div>
        <% end %>
      </div>

      <% flash.each do |name,msg| %>
        <%= content_tag(:div,msg,class:"alert") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

my_app/app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_img">
    <%= image_tag "blog1.jpg"%>
  </div>
  <div id="content">
    <h1>Hi,I'm Lakshit Dosi</h1>
    <p>Welcome to my blogs.In the past 3 days I built a blog in Rails.
      If you love my blogs please follow me so that you will be notified
       whenever I post a new one.</p>
  </div>
</div>

my_app/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count,"error") %> prevented this post from saving.</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

my_app/app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>


</div>

my_app/app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <p>created by <%= post.user.try(:email) %></p>
    <p class="date"><%= post.created_at.strftime("%b,%d,%Y") %></p>
  </div>
<% end %>
<%= will_paginate @posts %>

my_app/app/views/posts/new.html.erb
<div class="page_wrapper">
  <h1>New Post</h1>

  <%= render 'form' %>
</div>

my_app/app/views/posts/show.html.erb
<div id="post_content">

  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted by <%= @post.user.try(:email) %> <%= time_ago_in_words(@post.created_at) %> ago<br/><br/>
        <%= link_to "Edit", edit_post_path(@post) %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
  </p>
  <p class="body">
    <%= @post.body%>
  </p>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>